export const INIT_TEMPLATE = `# pnpm-deny.yaml is generated by \`pnpm deny init\`.
# This template covers the implemented licenses check. Other sections are
# reserved for later Policy Checks.

graph:
  exclude: []
  exclude-dev: false
  exclude-unpublished: false
  # Restrict the graph to packages that declare these platforms. Empty means all.
  os: []
  cpu: []
  libc: []

output:
  feature-depth: 1

licenses:
  # Licenses not listed here are denied.
  allow: []
  include-dev: false
  unused-allowed-license: warn
  unused-license-exception: warn
  exceptions: []
  # clarifications must bind an SPDX expression to integrity or commit.
  clarify: []
  private:
    # If true, skip license checks for Workspace Packages with "private": true.
    ignore: false
    # Skip license checks for External Packages from these sources.
    # Match the resolved registry URL (host), e.g.:
    #   ignore-sources:
    #     - https://npm.pkg.github.com
    ignore-sources: []
`;
