export const INIT_TEMPLATE = `# pnpm-deny.yaml is generated by \`pnpm deny init\`.
# This template covers the implemented licenses check. Other sections are
# reserved for later Policy Checks.

graph:
  exclude: []
  exclude-dev: false
  exclude-unpublished: false
  # Restrict the graph to packages that declare these platforms. Empty means all.
  os: []
  cpu: []
  libc: []

output:
  feature-depth: 1

licenses:
  # Licenses not listed here are denied.
  allow: []
  include-dev: false
  unused-allowed-license: warn
  unused-license-exception: warn
  exceptions: []
  # Override a package's license when the manifest is missing/wrong.
  # Must bind the expression to integrity (registry) or commit (git), e.g.:
  #   clarify:
  #     - package: ring@0.16.20
  #       expression: ISC AND MIT AND OpenSSL
  #       integrity: sha512-abc123...
  #     - package: some-git-dep@1.0.0
  #       expression: MIT
  #       commit: a1b2c3d4e5f6...
  clarify: []
  private:
    # If true, skip license checks for Workspace Packages with "private": true.
    ignore: false
    # Skip license checks for External Packages from these sources.
    # Match the resolved registry URL (host), e.g.:
    #   ignore-sources:
    #     - https://npm.pkg.github.com
    ignore-sources: []
`;
